fieldLayouts:
  4b9ea417-b82a-41ff-90fd-3f59e25eb65c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: Username
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3ad39fb4-78e4-4a15-9ebe-5b50591098d0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0a1f8dba-53e1-4eed-9276-b68c6a6b49ff # idShirt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b345e69a-ad29-45c4-8732-5996863e8312
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aa55fa09-c237-433c-ae5a-29eec1d62d10
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 185a17e8-7565-4f5a-8407-6438a77155ba
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 37122179-185c-42b0-a495-48f7f3cb0e55
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: f0bef74a-d0bf-428e-92d8-a1670e707ae3 # Likes
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
