fieldLayouts:
  4b9ea417-b82a-41ff-90fd-3f59e25eb65c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3ad39fb4-78e4-4a15-9ebe-5b50591098d0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 37122179-185c-42b0-a495-48f7f3cb0e55
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: f0bef74a-d0bf-428e-92d8-a1670e707ae3 # Likes
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
