dateModified: 1691870730
email:
  fromEmail: simon.terekhov@gmail.com
  fromName: t-react
  transportType: craft\mail\transportadapters\Sendmail
fs:
  imageshirt:
    hasUrls: true
    name: imageShirt
    settings:
      path: '@webroot/images/shirt'
    type: craft\fs\Local
    url: '@web/images/shirt'
meta:
  __names__:
    0a1f8dba-53e1-4eed-9276-b68c6a6b49ff: idShirt # idShirt
    0b78ac70-2a08-4c9e-81e2-21bae8339f60: t-react # t-react
    0fc9741f-19b6-4a55-a2b9-98bf35a7adca: shirtImage # shirtImage
    02b87d5e-eb2b-40d3-88ac-b28fe84bde20: Default # Default
    5f67af7d-f291-4014-9fc3-354454c419b2: Shirts # Shirts
    6e711eb9-f248-42e2-8c37-a467c26a3e91: Default # Default
    9cc51403-25f8-4780-a4f6-e972a87bc435: 'Front-end users' # Front-end users
    33bc150d-31e9-47c3-b25d-a813087f91f8: t-react # t-react
    c5fbbd8d-e6a5-485f-b279-015d8309feff: Common # Common
    e4cb0ec6-4050-4ba5-9ee8-0c906e00b90d: 'Public Schema' # Public Schema
    e25f7d77-50e7-4c26-a100-d5fd23800e5e: 'Private Schema' # Private Schema
    ea515821-b8cf-40b4-8de9-d08e73d13ad4: description # description
    f0bef74a-d0bf-428e-92d8-a1670e707ae3: Likes # Likes
plugins:
  graphql-authentication:
    edition: standard
    enabled: true
    licenseKey: 7X1KSNEL1QU6IKYYR4P8RIJL
    schemaVersion: 1.3.0
    settings:
      accountCooldown: 'Too many log in attempts; please try again shortly'
      accountDeleted: 'Successfully deleted account'
      accountLocked: 'Sorry, your account is currently locked'
      activationEmailSent: 'You will receive an email if it matches an account in our system'
      allowMagicAuthentication: null
      allowRegistration: '1'
      allowTwoFactorAuthentication: false
      allowedFacebookDomains: null
      allowedGoogleDomains: null
      allowedMicrosoftDomains: null
      allowedTwitterDomains: null
      appleClientId: null
      appleClientSecret: null
      appleRedirectUrl: null
      appleServiceId: null
      appleServiceSecret: null
      assetMutations: null
      assetNotFound: 'We couldn''t find any matching assets'
      assetQueries: null
      emailNotInScope: 'No email in scope'
      entryMutations:
        __assoc__:
          -
            - shirts
            - '1'
      entryNotFound: 'We couldn''t find any matching entries'
      entryQueries:
        __assoc__:
          -
            - shirts
            - ''
      facebookAppId: null
      facebookAppSecret: null
      facebookEmailMismatch: 'Email address doesn''t match allowed Facebook domains'
      facebookRedirectUrl: null
      fieldRestrictions:
        __assoc__:
          -
            - schema-1
            -
              __assoc__:
                -
                  - description
                  - queryMutate
          -
            - 'schema-Private Schema'
            -
              __assoc__:
                -
                  - description
                  - queryMutate
          -
            - 'schema-Public Schema'
            -
              __assoc__:
                -
                  - description
                  - queryMutate
      forbiddenField: 'User doesn''t have permission to access requested field(s)'
      forbiddenMutation: 'User doesn''t have permission to perform this mutation'
      googleClientId: null
      googleEmailMismatch: 'Email address doesn''t match allowed Google domains'
      googleTokenIdInvalid: 'Invalid Google Token ID'
      granularSchemas: null
      invalidEmailAddress: 'Invalid email address'
      invalidHeader: 'Invalid Authorization Header'
      invalidJwtSecretKey: 'Invalid JWT Secret Key'
      invalidLogin: 'We couldn''t log you in with the provided details'
      invalidMagicCode: 'Invalid magic code'
      invalidOauthToken: 'Invalid OAuth Token'
      invalidPasswordMatch: 'Passwords do not match'
      invalidPasswordUpdate: 'We couldn''t update the password with the provided details'
      invalidRefreshToken: 'Invalid Refresh Token'
      invalidRequest: 'Cannot validate request'
      invalidSchema: 'No schema has been set for this user group'
      invalidUserUpdate: 'We couldn''t update the user with the provided details'
      jwtExpiration: '1 day'
      jwtRefreshExpiration: '3 months'
      jwtSecretKey: uyKkuKU02hBjzQCX4qPvkC7c5SBci4nj
      magicLinkSent: 'You will receive an email if it matches an account in our system'
      microsoftAppId: null
      microsoftAppSecret: null
      microsoftEmailMismatch: 'Email address doesn''t match allowed Microsoft domains'
      microsoftRedirectUrl: null
      passwordResetRequired: 'Password reset required; please check your email'
      passwordResetSent: 'You will receive an email if it matches an account in our system'
      passwordSaved: 'Successfully saved password'
      passwordUpdated: 'Successfully updated password'
      permissionType: single
      sameSitePolicy: strict
      schemaId: null
      schemaName: 'Private Schema'
      siteId: null
      skipActivatedCheck: null
      skipSocialActivation: null
      tokenNotFound: 'We couldn''t find any matching tokens'
      twitterApiKey: null
      twitterApiKeySecret: null
      twitterEmailMismatch: 'Email address doesn''t match allowed Twitter domains'
      twitterRedirectUrl: null
      userActivated: 'Successfully activated user'
      userGroup: '1'
      userHasPassword: 'User not password-less'
      userNotActivated: 'Please activate your account'
      userNotFound: 'We couldn''t find any matching users'
      volumeNotFound: 'We couldn''t find any matching volumes'
system:
  edition: pro
  live: true
  name: t-react
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
