isPublic: true
name: 'Public Schema'
scope:
  - 'sites.33bc150d-31e9-47c3-b25d-a813087f91f8:read' # t-react
  - 'elements.drafts:read'
  - 'elements.revisions:read'
  - 'elements.inactive:read'
  - 'sections.5f67af7d-f291-4014-9fc3-354454c419b2:read' # Shirts
  - 'entrytypes.02b87d5e-eb2b-40d3-88ac-b28fe84bde20:read' # Default
